import Head from 'next/head'
import Image from 'next/image'
import styles from '@component/styles/Home.module.css'
import { useUser } from '@auth0/nextjs-auth0/client'
import { withPageAuthRequired } from '@auth0/nextjs-auth0'
import { Avatar, Button, Container, Grid } from '@mui/material';
import { deepOrange } from '@mui/material/colors';

export default function Home() {
  const { user, error, isLoading } = useUser();

  if (isLoading) return <>...Loading</>
  if (error) return <>Error!</>
  if (user) {
    return (
      <Container maxWidth="lg">
        <Head>
        <title>Travel Bud</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
        <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 3 }}>
        <Grid item xs={6}>
        <Image
            src="/logo-no-background.png"
            alt="Travel Bud Logo"
            width={100}
            height={70}/>
        </Grid>
        <Grid item xs={6}>
        <Avatar sx={{ bgcolor: deepOrange[500] }}>N</Avatar>

        </Grid>
        <Grid item xs={6}>
        <h2>Welcome {user.name}!</h2>
        </Grid>
        <Grid item xs={6}>
        <a href="/api/auth/logout">Logout</a>

        </Grid>
      </Grid>
          <Button variant="contained">Plan New Itinerary</Button>
        </main>
      </Container>
    )
  }
}

export const getServerSideProps = withPageAuthRequired();